In [84]:
import selenium                                  #library that is used to work with selenium
from selenium import webdriver                   #importing webdriver module from selenium to open automated chrome window
import pandas as pd                              #to create DataFrame
from selenium.webdriver.common.by import By      #importing inbuilt class By 
import warnings                                  #to ignore any sort of warning
warnings.filterwarnings("ignore")
import time  
from selenium.common.exceptions import NoSuchElementException
import requests
import regex as re

In [2]:
driver = webdriver.Chrome()

# Q1 Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [46]:
product=input("Enter your item: ")
print(product)

Enter your item: guitars
guitars

# Q2 In the above question, now scrape the following details of each product listed in first 3 pages of your search results
and save it in a data frame and csv. In case if any product has less than 3 pages in search results then
scrape all the products available under that product name. Details to be scraped are: "Brand
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [124]:
driver.get("https://www.amazon.in/")

In [56]:
search_bar=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
search_bar.send_keys('Guitar')

search_button=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search_button.click()

In [57]:
guitar_url=[]
start=0
end=3

for page in range(start,end):
    url=driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    for i in url:
        guitar_url.append(i.get_attribute('href'))
next_button=driver.find_element(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
next_button.click()

In [58]:
len(guitar_url)

186

In [59]:
brand=[]
product_name=[]
price=[]
replacement=[]
expected_delivery=[]
availability=[]
for i in guitar_url:
    driver.get(i)
    try:
        brnd=driver.find_element(By.XPATH,'//*[@id="productOverview_feature_div"]/div/table/tbody/tr[1]/td[2]/span')
        brand.append(brnd.text)
    except NoSuchElementException:
        brand.append('-')   
        
    try:
        prdct_nm=driver.find_element(By.XPATH,'//span[@id="productTitle"]')
        product_name.append(prdct_nm.text)
    except NoSuchElementException:
        product_name.append('-')
        
    try:
        prc=driver.find_element(By.XPATH,'//span[@class="a-price-whole"]')
        price.append(prc.text)
    except NoSuchElementException:
        price.append('-')
        
    try:
        replace=driver.find_element(By.XPATH,'//*[@id="iconfarmv2_feature_div"]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/ol/li[3]/div[1]/span/div[2]/span')
        replacement.append(replace.text)
    except NoSuchElementException:
        replacement.append('-')
        
    try:
        exp_del=driver.find_element(By.XPATH,'//*[@id="deliveryBlockContainer"]/div[1]/div[1]/div[1]/div[1]/span/span[1]')
        expected_delivery.append(exp_del.text)
    except NoSuchElementException:
        expected_delivery.append('-')
        
    try:
        avail=driver.find_element(By.XPATH,'//div[@class="a-section a-spacing-none a-spacing-top-micro }"]')
        availability.append(avail.text)
    except NoSuchElementException:
        availability.append('-')

In [68]:
df=pd.DataFrame({'Brand Name':brand,'Product Name':product_name,'Price':price,'Return/Exchange':replacement,'Expected Delivery':expected_delivery,'Availability':availability,'Product URL':guitar_url})
df

,Brand Name,Product Name,Price,Return/Exchange,Expected Delivery,Availability,Product URL
0,Kadence,Kadence A281 Professional Acoustic Rosewood gu...,"6,499",7 days Replacement,"Friday, 11 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,Kadence,"Kadence rosewood Guitar Frontier Series, Elect...","4,999",7 days Replacement,"Friday, 11 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kadence,Kadence Frontier guitar with Online Guitar lea...,"4,699",7 days Replacement,"Friday, 11 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Medellin,Medellin Acoustic Guitar (with guitar learning...,"2,499",7 days Replacement,"Friday, 11 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","1,799",7 days Replacement,"Sunday, 13 August",In stock,https://www.amazon.in/Juarez-Acoustic-Cutaway-...
...,...,...,...,...,...,...,...
181,NM Signature,NM Signature Electra Blue Rosewood Fretboard A...,"3,789",7 days Replacement,"Wednesday, 16 August",Only 2 left in stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
182,Kadence,Kadence Slowhand Premium Jumbo Semi Acoustic G...,"11,999",7 days Replacement,"Friday, 11 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
183,VAULT,Vault DA20 Dreadnought Acoustic Guitar With Gi...,"4,801",7 days Replacement,"Thursday, 10 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
184,Kaps,"Kaps ST - 1ACM, 6-Strings, Acoustic Guitar , R...","7,999",-,14 - 18 August,,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
185,Kadence,"Kadence Guitar Acoustica Series, Electric Acou...","6,999",7 days Replacement,"Friday, 11 August",In stock,https://aax-eu.amazon.in/x/c/RKecQIvnvoiE-3oxp...

# Q3 Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [92]:
driver.get("https://images.google.com/")

In [93]:
search_bar1=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_bar1.send_keys('Fruits')

search_button1=driver.find_element(By.XPATH,'//html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_button1.click()

In [94]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,50)")
    time.sleep(2)
    
images1=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

img_urls1=[]
for image1 in images1:
    source=image1.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls1.append(source)
            
for i in range(len(img_urls1)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i,10))
    response=requests.get(img_urls1[i])
    file=open(r"C:\Users\himani\Desktop\fliprobo_fruit"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [95]:
driver.get("https://images.google.com/")

In [96]:
search_bar2=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_bar2.send_keys('Cars')

search_button2=driver.find_element(By.XPATH,'//html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_button2.click()

In [97]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,50)")
    time.sleep(2)
    
images2=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

img_urls2=[]
for image2 in images2:
    source=image2.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls2.append(source)
            
for i in range(len(img_urls2)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i,10))
    response=requests.get(img_urls2[i])
    file=open(r"C:\Users\himani\Desktop\fliprobo_car"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [102]:
driver.get("https://images.google.com/")

In [103]:
search_bar3=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_bar3.send_keys('Machine Learning')

search_button3=driver.find_element(By.XPATH,'//html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_button3.click()

In [104]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,50)")
    time.sleep(2)
    
images3=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

img_urls3=[]
for image3 in images3:
    source=image3.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls3.append(source)
            
for i in range(len(img_urls3)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i,10))
    response=requests.get(img_urls3[i])
    file=open(r"C:\Users\himani\Desktop\fliprobo_ML"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [108]:
driver.get("https://images.google.com/")

In [109]:
search_bar4=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_bar4.send_keys('Guitar')

search_button4=driver.find_element(By.XPATH,'//html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_button4.click()

In [110]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,50)")
    time.sleep(2)
    
images4=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

img_urls4=[]
for image4 in images4:
    source=image4.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls4.append(source)
            
for i in range(len(img_urls4)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i,10))
    response=requests.get(img_urls4[i])
    file=open(r"C:\Users\himani\Desktop\fliprobo_guitar"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [117]:
driver.get("https://images.google.com/")

In [118]:
search_bar5=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/textarea')
search_bar5.send_keys('Cakes')

search_button5=driver.find_element(By.XPATH,'//html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button/div/span')
search_button5.click()

In [119]:
for _ in range(20):
    driver.execute_script("window.scrollBy(0,50)")
    time.sleep(2)
    
images5=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

img_urls5=[]
for image5 in images5:
    source=image5.get_attribute('src')
    if source is not None:
        if(source[0:4]=='http'):
            img_urls5.append(source)
            
for i in range(len(img_urls5)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i,10))
    response=requests.get(img_urls5[i])
    file=open(r"C:\Users\himani\Desktop\fliprobo_cake"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

# Q4 Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com
and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand
Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”,
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the
details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [76]:
driver.get("https://www.flipkart.com/")

In [77]:
search_bar6=driver.find_element(By.XPATH,'//input[@class="_3704LK"]')
search_bar6.send_keys('Oneplus Nord')

search_button6=driver.find_element(By.XPATH,'//button[@class="L0Z3Pu"]')
search_button6.click()

In [78]:
phone_url=[]
start=0
end=1

for page in range(start,end):
    url=driver.find_elements(By.XPATH,'//a[@class="_1fQZEK"]')
    for i in url:
        phone_url.append(i.get_attribute('href'))

In [79]:
len(phone_url)

24

In [80]:
brand_name=[]
smartphone_name=[]
colour=[]
ram=[]
rom=[]
primary_camera=[]
secondary_camera=[]
display_size=[]
battery_capacity=[]
price=[]
for i in phone_url:
    driver.get(i)
    try:
        brnd_nm=driver.find_element(By.XPATH,'//span[@class="B_NuCI"]')
        brand_name.append(brnd_nm.text.split(' ')[0])
    except NoSuchElementException:
        brand_name.append('-')   
    
    try:
        smrtphn_nm=driver.find_element(By.XPATH,'//span[@class="B_NuCI"]')
        smartphone_name.append(smrtphn_nm.text.split('(')[0])
    except NoSuchElementException:
        smartphone_name.append('-') 
        
    try:
        clr=driver.find_element(By.XPATH,'//span[@class="B_NuCI"]')
        colour.append(clr.text.split('(')[1].split(',')[0])
    except NoSuchElementException:
        colour.append('-')  
        
    try:
        rm=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li')
        ram.append(rm.text.split('|')[0])
    except NoSuchElementException:
        ram.append('-') 
        
    try:
        rm1=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li')
        rom.append(rm1.text.split('|')[1])
    except NoSuchElementException:
        rom.append('-')  
        
    try:
        prm_cm=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[3]')
        primary_camera.append(prm_cm.text.split('|')[0])
    except NoSuchElementException:
        primary_camera.append('-')  
        
    try:
        sec_cm=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[3]')
        secondary_camera.append(sec_cm.text)
    except NoSuchElementException:
        secondary_camera.append('-')
        
    try:
        dis_sz=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[2]')
        display_size.append(dis_sz.text.split('(')[0])
    except NoSuchElementException:
        display_size.append('-') 
        
    try:
        dis_sz=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[4]')
        battery_capacity.append(dis_sz.text)
    except NoSuchElementException:
        battery_capacity.append('-')
        
    try:
        prc=driver.find_element(By.XPATH,'//div[@class="_30jeq3 _16Jk6d"]')
        price.append(prc.text)
    except NoSuchElementException:
        price.append('-')

In [81]:
df1=pd.DataFrame({'Brand Name':brand_name,'Smartphone Name':smartphone_name,'Colour':colour,'RAM':ram,'“Storage(ROM)':rom,'Primary Camera':primary_camera,'Secondary Camera':secondary_camera,'Display Size':display_size,'Battery Capacity':battery_capacity,'Price':price,'Product URL':phone_url})
df1

,Brand Name,Smartphone Name,Colour,RAM,“Storage(ROM),Primary Camera,Secondary Camera,Display Size,Battery Capacity,Price,Product URL
0,OnePlus,OnePlus Nord CE 2 Lite 5G,Blue Tide,6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera | 16MP Front Camera,16.74 cm,5000 mAh Battery,"₹17,748",https://www.flipkart.com/oneplus-nord-ce-2-lit...
1,OnePlus,OnePlus Nord CE 2 Lite 5G,Black Dusk,6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera | 16MP Front Camera,16.74 cm,5000 mAh Battery,"₹17,685",https://www.flipkart.com/oneplus-nord-ce-2-lit...
2,OnePlus,OnePlus Nord 3 5G,Misty Green,16 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh Battery,"₹37,448",https://www.flipkart.com/oneplus-nord-3-5g-mis...
3,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera | 32MP Front Camera,17.02 cm,4500 mAh Battery,"₹28,499",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
4,OnePlus,OnePlus Nord 2T 5G,Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera | 32MP Front Camera,17.02 cm,4500 mAh Battery,"₹28,295",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
5,OnePlus,OnePlus Nord 3 5G,Tempest Gray,16 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh Battery,"₹37,134",https://www.flipkart.com/oneplus-nord-3-5g-tem...
6,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh Battery,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
7,OnePlus,OnePlus Nord 2T 5G,Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh Battery,"₹27,999",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
8,OnePlus,OnePlus Nord 2 5G,Blue Haze,12 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,16.33 cm,4500 mAh Battery,"₹34,990",https://www.flipkart.com/oneplus-nord-2-5g-blu...
9,OnePlus,OnePlus Nord 3 5G,Misty Green,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh Battery,"₹32,843",https://www.flipkart.com/oneplus-nord-3-5g-mis...
10,OnePlus,OnePlus Nord 3 5G,Tempest Gray,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh Battery,"₹32,713",https://www.flipkart.com/oneplus-nord-3-5g-tem...
11,OnePlus,OnePlus Nord CE3 5G,Grey Shimmer,12 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,5000 mAh Battery,"₹32,999",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
12,OnePlus,OnePlus Nord,Gray Onyx,6 GB RAM,64 GB ROM,48MP + 8MP,48MP + 8MP | 32MP + 8MP Dual Front Camera,16.36 cm,4115 mAh Battery,"₹22,890",https://www.flipkart.com/oneplus-nord-gray-ony...
13,OnePlus,OnePlus Nord 2 5G,PAC-MAN,12 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,16.33 cm,4500 mAh Battery,"₹37,999",https://www.flipkart.com/oneplus-nord-2-5g-pac...
14,OnePlus,OnePlus NORD CE2 LITE 5G,Blue Tide,6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera,16.74 cm,5000 mAh Battery,"₹17,997",https://www.flipkart.com/oneplus-nord-ce2-lite...
15,OnePlus,OnePlus Nord 2T 5G,Jade Fog,12 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh Battery,"₹33,990",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
16,OnePlus,OnePlus Nord CE 5G,Blue Void,8 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera,16.33 cm,4500 mAh Battery,"₹24,499",https://www.flipkart.com/oneplus-nord-ce-5g-bl...
17,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh Battery,"₹28,990",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
18,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh Battery,"₹28,988",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
19,OnePlus,OnePlus Nord CE 3 Lite 5G,Chromatic Gray,8 GB RAM,128 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh Battery,"₹17,890",https://www.flipkart.com/oneplus-nord-ce-3-lit...
20,OnePlus,OnePlus Nord CE 3 Lite 5G,Pastel Lime,8 GB RAM,128 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh Battery,"₹18,999",https://www.flipkart.com/oneplus-nord-ce-3-lit...
21,OnePlus,OnePlus Nord CE 3 Lite 5G,Pastel Lime,8 GB RAM,256 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh Battery,"₹21,499",https://www.flipkart.com/oneplus-nord-ce-3-lit...
22,OnePlus,OnePlus Nord CE 3 Lite 5G,Chromatic Gray,8 GB RAM,256 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh Battery,"₹21,249",https://www.flipkart.com/oneplus-nord-ce-3-lit...
23,OnePlus,OnePlus Nord,Gray Onyx,8 GB RAM,128 GB ROM,48MP + 8MP,48MP + 8MP | 32MP + 8MP Dual Front Camera,16.36 cm,4115 mAh Battery,"₹25,990",https://www.flipkart.com/oneplus-nord-gray-ony...

# Q5 Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [187]:
driver.get("https://www.google.com/maps/")

In [188]:
search_bar7=driver.find_element(By.XPATH,'//input[@class="searchboxinput xiQnY"]')
search_bar7.send_keys('Pune')

search_button7=driver.find_element(By.XPATH,'//button[@class="mL3xi"]')
search_button7.click()

In [189]:
try:
    url_string=driver.current_url
    print("URL Extracted: ",url_string)
    
    lat_lng=re.findall(r'@(.*)data',url_string)

    lat_lng_list=lat_lng[0].split(',')
    latitude=lat_lng_list[0]
    longitude=lat_lng_list[1]

    print("Latitude: ",latitude)
    print("Longitude: ",longitude)


except NoSuchElementException:
    print('-')

URL Extracted:  https://www.google.com/maps/place/Pune,+Maharashtra/@18.5245986,73.7805664,12z/data=!3m1!4b1!4m6!3m5!1s0x3bc2bf2e67461101:0x828d43bf9d9ee343!8m2!3d18.5204303!4d73.8567437!16zL20vMDE1eTJx?entry=ttu
Latitude:  18.5245986
Longitude:  73.7805664

# Q6 Write a program to scrap all the available details of best gaming laptops from digit.in.

In [245]:
driver.get("https://www.digit.in/")

In [246]:
search_laptops=driver.find_element(By.XPATH,'//span[@class="arrow_down laptops"]')
search_laptops.click()
search_best_laptops=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/div[2]/div/div[1]/span[4]/strong')
search_best_laptops.click()
search_best_gaming_laptops=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/div[2]/div/div[5]/div/div[2]/a/span')
search_best_gaming_laptops.click()

In [247]:
laptops_url=[]
url=driver.find_elements(By.XPATH,'//span[@class="datahreflink"]')
for i in url[0:7]:
    laptops_url.append(i.get_attribute('data-href'))

In [248]:
len(laptops_url)

7

In [249]:
laptop_name=[]
OS=[]
display_size=[]
processor=[]
memory=[]
price=[]
for i in laptops_url:
    driver.get(i)
    try:
        lpt_nm=driver.find_element(By.XPATH,'//div[@class="heading-wraper"]/h1')
        laptop_name.append(lpt_nm.text)
    except NoSuchElementException:
        laptop_name.append('-')   
        
    try:
        os=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[1]/div/p[2]/strong')
        OS.append(os.text)
    except NoSuchElementException:
        OS.append('-')  
        
    try:
        dsp_sz=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[2]/div/p[2]/strong')
        display_size.append(dsp_sz.text)
    except NoSuchElementException:
        display_size.append('-')
        
    try:
        prcs=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[3]/div/p[2]/strong')
        processor.append(prcs.text)
    except NoSuchElementException:
        processor.append('-')
        
    try:
        mry=driver.find_element(By.XPATH,'//div[@class="specs_details "]/ul/li[4]/div/p[2]/strong')
        memory.append(mry.text)
    except NoSuchElementException:
        memory.append('-')
        
    try:
        prc=driver.find_element(By.XPATH,'//div[@class="price_sec"]/div/h2/strong')
        price.append(prc.text)
    except NoSuchElementException:
        price.append('-')

In [250]:
df2=pd.DataFrame({'Laptop Name':laptop_name,'Operating System':OS,'Display SIze':display_size,'Processor':processor,'Memory':memory,'Price':price})
df2

,Laptop Name,Operating System,Display SIze,Processor,Memory,Price
0,HP Omen 17-ck2008TX 13th Gen Core i7-13700HX,Windows 11 Home,"17.3"" (2560 x 1440)",13th Gen Intel Core i7-13700HX | 5.0 GHz,1 TB SSD/16 GB DDR5,"₹ 269,777"
1,MSI GT77 Titan 12UHS-054IN 12th Gen Core i9-12...,Windows 11 Home,"17.3"" (3840 x 2160)",12th Gen Intel Core i9-12900HX | 3.6 GHz,2 TB SSD/64 GB DDR5,"₹ 499,990"
2,Lenovo Legion 5i Pro 12th Gen Core i7-12700H (...,Windows 11 Home,"16"" (2560 x 1600)",12th Gen Intel Core i7-12700H | 4.7 GHz,1 TB SSD/32 GB DDR5,"₹ 218,000"
3,ASUS ROG Strix Scar 18 G834JZ-N5041WS 13th Gen...,Windows 11 Home,"18"" (1920 x 1200)",13th Gen Intel Core i9-13980HX | 2.2 GHz,1 TB SSD/32 GB DDR5,"₹ 279,990"
4,Acer Predator Helios Neo 16 13th Gen Core i7-1...,Windows 11 Home,"16"" (2560 x 1600)",13th Gen Intel Core i7-13700HX | NA,1 TB SSD/16 GB DDR5,"₹ 149,990"
5,ASUS ROG Zephyrus G14 Ryzen 9-6900HS (GA402RJZ...,Windows 11 Home,"14"" (1920 x 1200)",AMD Ryzen 9-6900HS | 4.9 GHz,1 TB SSD/16 GB DDR5,"₹ 156,990"
6,MSI Cyborg 15 12th Gen Core i7-12650H (A12VF-2...,Windows 11 Home,"15.6"" (1920 x 1080)",12th Gen Intel Core i7-12650H | 4.7 GHz,1 TB SSD/16 GB DDR5,"₹ 130,990"

# Q7 Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [76]:
driver.get("https://www.forbes.com/")

In [296]:
search_button=driver.find_element(By.XPATH,'//div[@class="_8FT-x3t4"]')
search_button.click()
search_billionaires=driver.find_element(By.XPATH,'//div[@class="xMDGnUGv lXvj00YF pgYJ2orL"]/ul/li[2]/div/span')
search_billionaires.click()
search_worlds_billionaires=driver.find_element(By.XPATH,'//*[@class="xMDGnUGv"]/ul/li[1]')
search_worlds_billionaires.click()

In [297]:
rank=[]
name=[]
networth=[]
age=[]
country=[]
source=[]
industry=[]
try:
    rk=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[1]/div')
    rank.append(rk.text)
except NoSuchElementException:
    rank.append('-')

try:
    nm=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[2]/div')
    name.append(nm.text)
except NoSuchElementException:
    name.append('-')
    
try:
    ntwrt=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[3]/div')
    networth.append(ntwrt.text)
except NoSuchElementException:
    networth.append('-')
    
try:
    ag=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[4]/div')
    age.append(ag.text)
except NoSuchElementException:
    age.append('-')
    
try:
    cntry=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[5]')
    country.append(cntry.text)
except NoSuchElementException:
    country.append('-')
    
try:
    src=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[6]/div')
    source.append(src.text)
except NoSuchElementException:
    source.append('-')
    
try:
    idstr=driver.find_element(By.XPATH,'//div[@class="TableRow_row__L-0Km TableRow_activeRow__g4oSF"]/div[7]/div')
    industry.append(idstr.text)
except NoSuchElementException:
    industry.append('-')

In [298]:
df3=pd.DataFrame({'Rank':rank,'Name':name,'Networth':networth,'Age':age,'Country':country,'Source':source,'Industry':industry})
df3

  Rank                      Name Networth Age Country Source          Industry
0    1  Bernard Arnault & family   $211 B  74  France   LVMH  Fashion & Retail

In [302]:
rank1=[]
name1=[]
networth1=[]
age1=[]
country1=[]
source1=[]
industry1=[]
try:
    rk1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[1]/div')
    for i in rk1:
        rank1.append(i.text)
except NoSuchElementException:
    rank1.append('-')

try:
    nm1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[2]/div')
    for i in nm1:
        name1.append(i.text)
except NoSuchElementException:
    name1.append('-')
    
try:
    ntwrt1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[3]/div')
    for i in ntwrt1:
        networth1.append(i.text)
except NoSuchElementException:
    networth1.append('-')
    
try:
    ag1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[4]/div')
    for i in ag1:
        age1.append(i.text)
except NoSuchElementException:
    age1.append('-')
    
try:
    cntry1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[5]')
    for i in cntry1:
        country1.append(i.text)
except NoSuchElementException:
    country1.append('-')
    
try:
    src1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[6]/div')
    for i in src1:
        source1.append(i.text)
except NoSuchElementException:
    source1.append('-')
    
try:
    idstr1=driver.find_elements(By.XPATH,'//*[@class="TableRow_row__L-0Km"]/div[7]/div')
    for i in idstr1:
        industry1.append(i.text)
except NoSuchElementException:
    industry1.append('-')

In [325]:
df4=pd.DataFrame({'Rank':rank1,'Name':name1,'Networth':networth1,'Age':age1,'Country':country1,'Source':source1,'Industry':industry1})
df4

,Rank,Name,Networth,Age,Country,Source,Industry
0,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
1,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
2,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
3,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
4,6,Bill Gates,$104 B,67,United States,Microsoft,Technology
...,...,...,...,...,...,...,...
194,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
195,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
196,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
197,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
198,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

In [326]:
results=pd.concat([df3,df4],ignore_index=True)
results

,Rank,Name,Networth,Age,Country,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail
1,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
2,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
3,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
4,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
196,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
197,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
198,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
199,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

# Q8 Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [3]:
driver.get("https://www.youtube.com/watch?v=Op4EMZXWjyE")
time.sleep(10)

In [4]:
comment=[]
comment_upvote=[]
comment_time=[]

for _ in range(100):
    driver.execute_script("window.scrollBy(0,600)")
    time.sleep(10)

cmnt=driver.find_elements(By.XPATH,'//div[@id="comment-content"]')
for i in cmnt[0:500]:
    comment.append(i.text)
    
cmnt_uv=driver.find_elements(By.XPATH,'//span[@id="vote-count-middle"]')
for i in cmnt_uv[0:500]:
    comment_upvote.append(i.text)
    
tm=driver.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]')
for i in tm[0:500]:
    comment_time.append(i.text)

In [5]:
print(len(comment),len(comment_upvote),len(comment_time))

500 500 500

In [6]:
df5=pd.DataFrame({'Comment':comment,'Comment Upvote':comment_upvote,'Time':comment_time})
df5

,Comment,Comment Upvote,Time
0,Bestest song I've ever heard. This song got th...,9,1 day ago (edited)
1,one of the best singer in punjabi singers...,2,19 hours ago
2,I'm so glad he's finally getting the recogniti...,269,2 months ago
3,One of the most underrated star. Should have g...,5,1 day ago
4,Addicted to his every song .how a person be so...,37,2 weeks ago (edited)
...,...,...,...
495,fan of @prophec for centuries,1,1 month ago
496,Whenever I hear of this song surround myself w...,5,2 weeks ago
497,Heart touching love song ️️️,1,1 month ago
498,Literally everything about this song is just p...,8,5 months ago (edited)
499,Best Song,,2 months ago (edited)

# Q9 Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in“London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overallreviews, privates from price, dorms from price, facilities and property description

In [108]:
driver.get("https://www.hostelworld.com/")

In [109]:
search_bar=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
search_bar.send_keys('London')

In [110]:
search_found=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]')
search_found.click()
time.sleep(2)

In [111]:
search=driver.find_element(By.XPATH,'//button[@class="btn-content large-button icon-only"]')
search.click()
time.sleep(2)

In [114]:
hostel_url=[]
url=driver.find_elements(By.XPATH,'//a[@class="nuxt-link"]')
for i in url[2:32]:
    hostel_url.append(i.get_attribute('href'))

In [115]:
len(hostel_url)

30

In [116]:
distance=[]
try:
    dis=driver.find_elements(By.XPATH,'//span[@class="distance-description"]')
    for i in dis:
        distance.append(i.text.split('-')[1])
except NoSuchElementException:
    distance.append('-')

In [ ]:
hostel_name=[]
ratings=[]
total_reviews=[]
overall_reviews=[]
facilities=[]
property_description=[]
for i in hostel_url:
    driver.get(i)   
    try:
        hstnm=driver.find_elements(By.XPATH,'//div[@class="title-2"]')
        hostel_name.append(hstnm.text)
    except NoSuchElementException:
        hostel_name.append('-')
        
    try:
        rate=driver.find_elements(By.XPATH,'//*[@class="reviews-and-ratings"]/div[1]/div[1]/div')
        ratings.append(rate.text)
    except NoSuchElementException:
        ratings.append('-')
        
    try:
        tr=driver.find_elements(By.XPATH,'//div[@class="reviews-and-ratings"]/div[1]/div[1]/div[2]/div[2]')
        total_reviews.append(tr.text)
    except NoSuchElementException:
        total_reviews.append('-')
        
    try:
        ovrv=driver.find_elements(By.XPATH,'//div[@class="reviews-and-ratings"]/div[1]/div[1]/div[2]/div/span')
        overall_reviews.append(ovrv.text)
    except NoSuchElementException:
        overall_reviews.append('-')
        
    try:
        fac=driver.find_elements(By.XPATH,'//*[@class="facilities-container"]/ul[1]/li[1]/ul[1]')
        facilities.append(fac.text)
    except NoSuchElementException:
        facilities.append('-')
        
    try:
        pd=driver.find_elements(By.XPATH,'//*[@class="description-container"]/div[1]/div[2]')
        property_description.append(ipdtext)
    except NoSuchElementException:
        property_description.append('-')

In [ ]:
df6=pd.DataFrame({'Hostel Name':hostel_name,'Distance from city centre':distance,'Ratings':ratings,'Total Review':total_reviews,'Overall Reviews':overall_reviews,'facilities':facilities,'Property Description':property_description})
df6